#usage:
#docker-compose up -d (백그라운드로 구동)
#docker-compose down
#-p <project name>
#docker-compose -p drupal up -d
#docker-compose -p drupal down
#docker-compose -p drupal -f ./docker-compose-drupal.yml up -d
#docker-compose -p drupal -f ./docker-compose-drupal.yml down

version: '3.1'
services:
  postgres-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - /postgres_db_for_drupal:/var/lib/postgresql/data
  web:
    depends_on:
      - postgres-db
    links:
      - postgres-db:postgres
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    ports:
      - "80:80"
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: